// languages/javascript/archive/younetmedia.com/src/components/Navbar/index.tsx
import Link from 'next/link';
import { useRouter } from 'next/router';
import { FC } from 'react';

export const Navbar: FC = () => {
  const router = useRouter();

  const logOut = () => {
    sessionStorage.setItem('accessToken', '');
    router.push('/auth');
  };

  return (
    <nav className="border-b shadow">
      <div className="container mx-auto px-8 py-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-x-2">
            <Link href="/">
              <h1 className="uppercase">Buzz Metrics</h1>
            </Link>
            <Link href="/socialheat">
              <p>Social Heat</p>
            </Link>
            <Link href="/socialtrend">
              <p>Social Trend</p>
            </Link>
          </div>
          <div>
            <button
              type="button"
              onClick={logOut}
              className="btn bg-blue-500 uppercase text-white">
              Log Out
            </button>
          </div>
        </div>
      </div>
    </nav>
  );
};

// concepts/typescript/frontend/solid/client/src/components/organisms/Navbar/index.tsx
import Container from '@suid/material/Container';
import { Component } from 'solid-js';
import Link from '../../atoms/Link';
import UserMenu from '../../molecules/UserMenu';

export const Navbar: Component = () => {
  return (
    <nav>
      <div class="border-b py-8">
        <Container>
          <div class="flex items-center justify-between">
            <div class="flex items-center gap-4 uppercase">
              <h1 class="text-2xl">
                <Link href="/apps">Solid</Link>
              </h1>
              <Link href="/apps/chart">Chart</Link>
              <Link href="/apps/table">Table</Link>
              <Link href="/apps/calendar">Calendar</Link>
            </div>
            <div>
              <UserMenu />
            </div>
          </div>
        </Container>
      </div>
    </nav>
  );
};

export default Navbar;
