// languages/typescript/frontend/solid/client/src/pages/404.tsx
import Button from '@suid/material/Button';
import type { Component } from 'solid-js';
import Link from '../components/atoms/Link';

const NotFoundPage: Component = () => {
  return (
    <main class="flex h-screen w-full items-center justify-center">
      <div class="flex flex-col gap-4 text-center uppercase">
        <h1 class="text-9xl font-bold">404</h1>
        <p class="text-3xl">Page Not Found</p>
        <Link href="/">
          <Button variant="contained" fullWidth>
            Back to Home
          </Button>
        </Link>
      </div>
    </main>
  );
};

export default NotFoundPage;

// concepts/typescript/frontend/react/server/gatsby/src/pages/404.tsx
import { HeadFC, PageProps } from 'gatsby';
import * as React from 'react';

const NotFoundPage: React.FC<PageProps> = () => {
  return (
    <main className="flex h-screen w-full flex-col items-center justify-center gap-4">
      <h1 className="text-9xl font-bold">404</h1>
      <p className="text-3xl uppercase">Page Not Found</p>
    </main>
  );
};

export default NotFoundPage;

export const Head: HeadFC = () => <title>Gatsby Template - Not found</title>;
