// concepts/typescript/frontend/react/server/next/src/templates/LayoutTemplate/index.tsx
import { ReactNode } from 'react';
import Footer from '../../components/organisms/Footer';
import Navbar from '../../components/organisms/Navbar';

export type LayoutTemplateProps = {
  children?: ReactNode;
};

export const LayoutTemplate: React.FC<LayoutTemplateProps> = ({
  children = <></>
}) => {
  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />
      <main className="grow">{children}</main>
      <Footer />
    </div>
  );
};

export default LayoutTemplate;

// languages/typescript/frontend/solid/client/src/templates/LayoutTemplate/index.tsx
import { Component, JSX, mergeProps } from 'solid-js';
import Footer from '../../components/organisms/Footer';
import Navbar from '../../components/organisms/Navbar';

export type LayoutTemplateProps = {
  children?: JSX.Element;
};

export const LayoutTemplate: Component<LayoutTemplateProps> = (_props) => {
  const props = mergeProps({ children: <></> }, _props);
  return (
    <div class="flex min-h-screen flex-col">
      <Navbar />
      <main class="grow">{props.children}</main>
      <Footer />
    </div>
  );
};

export default LayoutTemplate;
