// languages/typescript/frontend/solid/server/src/components/organisms/Footer/index.tsx
import Container from '@suid/material/Container';
import { Component } from 'solid-js';

export const Footer: Component = () => {
  return (
    <footer>
      <div class="border-t py-8">
        <Container>
          <p>&copy; 2023 Solid</p>
        </Container>
      </div>
    </footer>
  );
};

export default Footer;

// concepts/typescript/frontend/react/client/react/src/components/organisms/Footer/index.tsx
import Container from '@mui/material/Container';
import React from 'react';

export const Footer: React.FC = () => {
  return (
    <footer>
      <div className="border-t py-8">
        <Container>
          <p>&copy; 2023 Solid</p>
        </Container>
      </div>
    </footer>
  );
};

export default Footer;
